const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const supabase = require('../lib/supabase');

router.get('/:sessionId', async (req, res) => {
  try {
    const { data: session, error } = await supabase
      .from('sessions')
      .select('*')
      .eq('id', req.params.sessionId)
      .single();

    if (error || !session) {
      return res.status(404).json({ error: 'Session not found' });
    }

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=truveil-report-${session.id}.pdf`);
    doc.pipe(res);

    // Header
    doc.fontSize(24).font('Helvetica-Bold').text('Truveil Interview Report', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).font('Helvetica').fillColor('#666')
      .text(`Session: ${session.id}  •  Generated: ${new Date().toISOString().split('T')[0]}`, { align: 'center' });
    doc.moveDown(1);

    // Divider
    doc.strokeColor('#ddd').lineWidth(0.5)
      .moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(1);

    // Session Info
    doc.fillColor('#000').fontSize(14).font('Helvetica-Bold').text('Session Details');
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').fillColor('#333');
    doc.text(`Status: ${session.status}`);
    doc.text(`Created: ${session.created_at}`);
    if (session.ended_at) doc.text(`Ended: ${session.ended_at}`);
    doc.moveDown(1);

    // Flags Summary
    const flags = session.flags || [];
    doc.fillColor('#000').fontSize(14).font('Helvetica-Bold').text(`Flags Detected (${flags.length})`);
    doc.moveDown(0.3);

    if (flags.length === 0) {
      doc.fontSize(10).font('Helvetica').fillColor('#666').text('No flags were detected during this session.');
    } else {
      flags.forEach((flag, i) => {
        doc.fontSize(10).font('Helvetica-Bold').fillColor('#cc0000')
          .text(`${i + 1}. ${flag.type || 'FLAG'}`, { continued: true });
        doc.font('Helvetica').fillColor('#333')
          .text(` — ${flag.detail || 'No detail'}`);
        if (flag.timestamp) {
          doc.fontSize(8).fillColor('#999').text(`   at ${new Date(flag.timestamp).toLocaleTimeString()}`);
        }
        doc.moveDown(0.2);
      });
    }
    doc.moveDown(1);

    // Transcript
    const transcript = session.transcript || [];
    doc.fillColor('#000').fontSize(14).font('Helvetica-Bold').text('Full Transcript');
    doc.moveDown(0.3);

    if (transcript.length === 0) {
      doc.fontSize(10).font('Helvetica').fillColor('#666').text('No transcript data recorded.');
    } else {
      transcript.forEach((entry) => {
        const time = entry.timestamp ? new Date(entry.timestamp).toLocaleTimeString() : '--:--';
        const score = entry.score != null ? entry.score : '-';
        doc.fontSize(9).font('Helvetica-Bold').fillColor('#000')
          .text(`[${time}]  AI Score: ${score}%`);
        doc.fontSize(10).font('Helvetica').fillColor('#333')
          .text(entry.text || '', { indent: 10 });
        doc.moveDown(0.5);
      });
    }

    // Footer
    doc.moveDown(2);
    doc.strokeColor('#ddd').lineWidth(0.5)
      .moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(0.5);
    doc.fontSize(8).font('Helvetica').fillColor('#999')
      .text('Generated by Truveil — truveil.com — This report is confidential.', { align: 'center' });

    doc.end();
  } catch (err) {
    console.error('Report generation error:', err);
    res.status(500).json({ error: 'Failed to generate report' });
  }
});

module.exports = router;
